apiVersion: v1
kind: Service
metadata:
  name: eventgenerator
  labels:
    app: eventgenerator
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.170.0.0/16
  ports:
  - name: http-server
    port: 80
    targetPort: http-server
  selector:
    app: eventgenerator